"""Read map.json back into a queryable index; provenance + freshness.

The map subcommand stamps map.json with provenance (tool version, git
commit, discovery options, per-file content hashes). Read commands load
the document into a ``MapIndex`` and compare provenance against the
working tree to decide whether the map is still fresh.
"""

import hashlib
import json
import os
import re
import subprocess
import tempfile
from collections import Counter
from collections.abc import Callable, Iterator
from dataclasses import dataclass, field
from importlib.metadata import version as _pkg_version
from pathlib import Path

from dekko.core import walker
from dekko.classify import is_test_path
from dekko.core.languages import spec_fingerprint
from dekko.core.model import (
    CallGraph,
    CatchSite,
    EnvRead,
    ExternalCall,
    FileMap,
    Import,
    Param,
    Symbol,
)

try:
    import orjson
except ImportError:  # pragma: no cover - exercised in stdlib-only envs
    orjson = None  # type: ignore[assignment]

try:
    import orjson
except ImportError:  # pragma: no cover - exercised in stdlib-only envs
    orjson = None  # type: ignore[assignment]

MAP_DOC_VERSION = 11
_MAP_DIR = ".dekko"


class MapFormatTooNewError(Exception):
    """``map.json``'s ``"version"`` is newer than this build supports.

    Raised by ``load_map`` instead of letting a downstream shape
    mismatch (e.g. an interned-id integer fed to code that still
    expects a string) raise its own opaque, unrelated-looking
    exception. This is the reading side of a version skew: a
    long-lived process (``dekko serve --mcp``, the daemon) keeps its
    parsing code in memory for its whole lifetime, so it can fall
    behind a ``map.json`` regenerated by a newer ``dekko`` build
    (another process, or this session's own ``refresh_map``) without
    ever reloading. See ``.features/fixes/stale-map-json-mcp-crash.md``.
    """


class MapFormatInvalidError(Exception):
    """``map.json``'s ``"version"`` field is missing a valid integer.

    Raised by ``load_map`` when the top-level ``"version"`` value is
    present but not an ``int`` (``null``, a string, a float, ...) —
    a malformed or corrupted document, not merely a newer one. This
    is deliberately a distinct exception from
    ``MapFormatTooNewError``: "too new" implies a valid, well-formed
    document this build doesn't yet understand (fix: upgrade dekko
    or restart the long-lived process reading it), whereas a
    non-numeric ``"version"`` means the document itself is broken
    (fix: regenerate it with ``dekko map``). Without this guard, the
    bad value flows into ``doc_version > MAP_DOC_VERSION`` and raises
    an opaque ``TypeError`` instead — the same failure mode
    ``MapFormatTooNewError`` exists to prevent, just for a different
    kind of bad input. See
    ``.features/fixes/stale-map-json-mcp-crash.md``.
    """


_BASE_SPLIT = re.compile(r"::|\.|->|/")
_UNSUPPORTED_PREFIX = "no parser ("
_VENDORED_PREFIX = "vendored ("
_TOO_LARGE_REASON = "too large"
# Cap on how many "too large" paths a coverage note names outright —
# unlike no-grammar/vendored skips (which can number in the hundreds
# and are only ever shown as aggregate counts), an oversized file is
# rare enough that naming it is exactly the useful signal (round-18
# zed finding: an agent hit "no mapped file" on a real, first-party
# 1.3 MB test file with zero indication a size cap was the reason).
_MAX_TOO_LARGE_PATHS = 10
_PROVENANCE_FILE = "provenance.json"


def _json_loads(data: bytes) -> object:
    """Parse JSON bytes, preferring ``orjson`` (2-10x faster) when
    installed (the ``dekko[fastjson]`` extra); falls back to stdlib
    ``json`` otherwise. Both raise a ``ValueError`` subclass on bad
    input, so callers can catch ``ValueError`` uniformly regardless of
    which backend is active.
    """
    if orjson is not None:
        return orjson.loads(data)
    return json.loads(data)


def _json_dumps(obj: object) -> bytes:
    """Serialize to compact JSON bytes, preferring ``orjson`` when
    installed; falls back to stdlib ``json``. Used for machine-only
    files (the provenance sidecar, ``map.json`` as of round 15) where
    human-readable indentation doesn't matter. The stdlib fallback
    passes ``separators=(",", ":")`` — without it, ``json.dumps``
    still inserts a space after every ``,``/``:`` even with no
    ``indent``, which is real, avoidable overhead on documents with
    millions of small array elements (exactly ``map.json``'s shape on
    a large repo). ``orjson.dumps`` has no such padding by default, so
    only the stdlib branch needs the explicit argument.
    """
    if orjson is not None:
        return orjson.dumps(obj)
    return json.dumps(obj, separators=(",", ":")).encode("utf-8")


def build_id_table(graph: CallGraph) -> tuple[list[str], dict[str, int]]:
    """First-appearance-order intern table for id strings the writer
    repeats across ``"edges"``/``"ambiguous"``/``"external"``/
    ``"referenced"``/``"heritage"``/``"heritage_ambiguous"``/
    ``"heritage_external"``/``"throws"``/``"throws_ambiguous"``/
    ``"throws_external"``/``"throws_bare"``/``"catches"``.

    ``"ambiguous"`` entries in particular can each name dozens to
    thousands of candidate ids that also appear, verbatim, in many
    other entries (round-15 plan: a measured 463.6x duplication factor
    on zed's ``ambiguous`` section, 89.6% of that map.json's total
    bytes). Building one shared table and writing every distinct id
    string once, referenced elsewhere by integer index, is what
    collapses that duplication. ``"symbols"[].id`` is deliberately not
    covered here — it's the primary key readers already look records
    up by as a string, and it is not where the disproportionate size
    lives (round-15 plan's non-goals).

    Args:
        graph: Resolved call graph whose edge/ambiguous/external/
            referenced sections will be written.

    Returns:
        ``(ids, index)``: ``ids`` is the ordered list to embed as the
        document's top-level ``"ids"`` key; ``index`` is the
        ``str -> int`` lookup the writer uses while serializing.
    """
    ids: list[str] = []
    index: dict[str, int] = {}

    def intern(value: str) -> None:
        if value not in index:
            index[value] = len(ids)
            ids.append(value)

    for edge in graph.edges:
        intern(edge.caller)
        intern(edge.callee)
    for caller, _name, candidates in graph.ambiguous:
        intern(caller)
        for cand in candidates:
            intern(cand)
    for ext in graph.external:
        intern(ext.caller)
        intern(ext.callee)
    for edge in graph.referenced:
        intern(edge.caller)
        intern(edge.callee)
    _intern_heritage(graph, intern)
    _intern_modules(graph, intern)
    _intern_throws_catches(graph, intern)
    return ids, index


def _intern_heritage(graph: CallGraph, intern: Callable[[str], None]) -> None:
    """The ``build_id_table`` interning loops for heritage sections.

    Split out from ``build_id_table`` itself purely to keep that
    function's cyclomatic complexity under the project's Ruff limit —
    behaviorally this is still the same first-appearance-order
    interning pass, just for ``"heritage"``/``"heritage_ambiguous"``/
    ``"heritage_external"`` instead of the call-graph sections.
    """
    for edge in graph.heritage:
        intern(edge.subtype)
        intern(edge.supertype)
    for subtype, _name, cands in graph.heritage_ambiguous:
        intern(subtype)
        for cand in cands:
            intern(cand)
    for ext in graph.heritage_external:
        intern(ext.caller)
        intern(ext.callee)


def _intern_modules(graph: CallGraph, intern: Callable[[str], None]) -> None:
    """The ``build_id_table`` interning loop for the module graph.

    Interns file *paths* (not symbol ids) from ``graph.modules`` —
    safe to share the same intern table as every symbol-id section
    above, since a path string never collides with a symbol id string
    (every symbol id contains ``"::"``; no repo-relative path does).
    Only the edges' ``importer``/``imported`` paths are interned, per
    the design's own scoping — ``ModuleGraph.external``'s *values*
    (raw unresolved import-source text, e.g. ``"os"``) are not paths
    and are written as plain strings.
    """
    for edge in graph.modules.edges:
        intern(edge.importer)
        intern(edge.imported)
    for path in graph.modules.external:
        intern(path)


def _intern_throws_catches(
    graph: CallGraph, intern: Callable[[str], None]
) -> None:
    """The ``build_id_table`` interning loops for throws/catches.

    Split out of ``build_id_table`` for the same reason
    ``_intern_heritage``/``_intern_modules`` are — keeps that
    function's cyclomatic complexity under the project's Ruff limit.
    Interns caller/type ids from ``"throws"``/``"throws_ambiguous"``/
    ``"throws_external"``/``"throws_bare"``/``"catches"`` — a caller id
    here is a symbol id or a module pseudo-id
    (``resolver.MODULE_CALLER_SUFFIX``), safe to share the same table
    every other section already interns caller ids into.
    """
    for edge in graph.throws:
        intern(edge.caller)
        intern(edge.type)
    for caller, _name, cands in graph.throws_ambiguous:
        intern(caller)
        for cand in cands:
            intern(cand)
    for ext in graph.throws_external:
        intern(ext.caller)
        intern(ext.callee)
    for caller, _path, _line in graph.throws_bare:
        intern(caller)
    for site in graph.catches:
        intern(site.caller)
        for type_id in site.repo_types.values():
            intern(type_id)


def _resolve_ref(value: object, ids: list[str] | None) -> str:
    """Resolve one caller/callee/candidate field to its string id.

    Pre-v5 documents store the id directly as a string; v5+ documents
    store an integer index into the document's top-level ``"ids"``
    table (``ids`` is non-``None`` only then, see ``load_map``).
    Centralizing this one branch on ``isinstance`` (not truthiness) is
    what lets every read loop below stay ignorant of which on-disk
    shape it's reading, without a falsy-zero bug: index ``0`` is a
    perfectly valid interned id and must not be treated as "missing"
    the way ``value or ""`` would.

    Args:
        value: Raw field value as parsed from JSON — a string
            (pre-v5) or an integer index (v5+).
        ids: The document's id table, or ``None`` for pre-v5 reads.

    Returns:
        The resolved id string, or ``""`` when ``value`` doesn't match
        the shape ``ids`` implies (missing/malformed field).
    """
    if ids is None:
        return value if isinstance(value, str) else ""
    return ids[value] if isinstance(value, int) else ""


def atomic_write_bytes(path: Path, data: bytes) -> None:
    """Write ``data`` to ``path`` without ever exposing a partial file.

    Writes to a sibling temp file in the same directory, then
    ``os.replace()``s it into place — a single filesystem-level rename
    rather than an in-place ``write_text``/``write_bytes``. The
    temp file lives alongside ``path`` (not in a system temp dir) so
    the rename is guaranteed atomic (same filesystem).

    Without this, a reader (``load_map``, a concurrent daemon/MCP/CLI
    process's own regen) that opens ``path`` mid-write can observe
    however many bytes the writer has flushed so far — a truncated
    ``map.json``/``cache.json`` that fails JSON parsing outright, or
    worse, parses successfully as a valid-but-incomplete document.
    Round-12 master report §4.1b: no synchronization primitive of any
    kind previously guarded these writes, and multiple independent
    processes (bare CLI, daemon-triggered regen, MCP server) can each
    trigger one against the same root with zero coordination. Atomic
    replacement doesn't prevent two writers from racing each other,
    but it guarantees every reader sees either the old complete file
    or the new complete file, never a half-written one.

    Args:
        path: Destination file path; parent directory must exist.
        data: Exact bytes to write.
    """
    fd, tmp_name = tempfile.mkstemp(
        dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "wb") as tmp_file:
            tmp_file.write(data)
        os.replace(tmp_name, path)
    except BaseException:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


def _unsupported_summary(
    skipped: list[tuple[str, str]] | None,
) -> dict | None:
    """Aggregate ``walker.discover``'s skip reasons into a coverage note.

    Only ``"no parser (<language>)"`` reasons are counted here — the
    confirmed language-support gaps recorded in
    ``languages.KNOWN_UNSUPPORTED`` — not the ordinary
    ``"excluded"``/``"generated"``/``"too large"`` skips a repo owner
    asked for or expects. This is what lets a "no callers found"
    answer be qualified as "no callers among parsed files" instead of
    presented as unconditional truth (see ``query`` module).

    Args:
        skipped: ``(path, reason)`` pairs from ``walker.discover``.

    Returns:
        ``{"count": N, "languages": {lang: N, ...}}``, or ``None``
        when there is nothing to report.
    """
    if not skipped:
        return None
    by_lang: Counter[str] = Counter()
    for _, reason in skipped:
        if reason.startswith(_UNSUPPORTED_PREFIX) and reason.endswith(")"):
            by_lang[reason[len(_UNSUPPORTED_PREFIX) : -1]] += 1
    if not by_lang:
        return None
    return {
        "count": sum(by_lang.values()),
        "languages": dict(sorted(by_lang.items())),
    }


def _vendored_summary(
    skipped: list[tuple[str, str]] | None,
) -> dict | None:
    """Aggregate ``walker.discover``'s ``"vendored (<dir>)"`` reasons.

    Mirrors ``_unsupported_summary`` but for files skipped solely
    because they live under a default-excluded directory that
    occasionally holds first-party code (``node_modules``, ``vendor``,
    ``third_party``, ``target``, ``dist``, ``build`` — see
    ``walker._VENDORED_DIRS``), as opposed to VCS metadata/tool caches
    (``walker._NOISE_DIRS``) where silence is correct and
    ``walker.discover`` never even records a skip entry.

    Args:
        skipped: ``(path, reason)`` pairs from ``walker.discover``.

    Returns:
        ``{"count": N, "dirs": {name: N, ...}}``, or ``None`` when
        there is nothing to report.
    """
    if not skipped:
        return None
    by_dir: Counter[str] = Counter()
    for _, reason in skipped:
        if reason.startswith(_VENDORED_PREFIX) and reason.endswith(")"):
            by_dir[reason[len(_VENDORED_PREFIX) : -1]] += 1
    if not by_dir:
        return None
    return {
        "count": sum(by_dir.values()),
        "dirs": dict(sorted(by_dir.items())),
    }


def _too_large_summary(
    skipped: list[tuple[str, str]] | None,
) -> dict | None:
    """Aggregate ``walker.discover``'s ``"too large"`` reasons.

    Unlike ``_unsupported_summary``/``_vendored_summary`` (which only
    ever report aggregate counts, since a no-grammar or vendored-dir
    skip can span hundreds of files), this names the actual paths —
    an oversized-file skip is rare enough that the path itself is the
    useful signal, and round-18's zed report found an agent had no way
    to learn *which* first-party file a plain "no mapped file or
    directory" error was actually hiding.

    Args:
        skipped: ``(path, reason)`` pairs from ``walker.discover``.

    Returns:
        ``{"count": N, "paths": [...]}`` (paths capped at
        ``_MAX_TOO_LARGE_PATHS``, sorted), or ``None`` when there is
        nothing to report.
    """
    if not skipped:
        return None
    paths = sorted(
        path for path, reason in skipped if reason == _TOO_LARGE_REASON
    )
    if not paths:
        return None
    return {
        "count": len(paths),
        "paths": paths[:_MAX_TOO_LARGE_PATHS],
    }


def format_unsupported(provenance: dict | None) -> str | None:
    """Coverage note(s) from a provenance dict's skip aggregates.

    Combines three independent coverage gaps into one caller-facing
    note, each included only when present: confirmed-unsupported
    languages (``provenance["unsupported"]``), files skipped only
    because they live under a default-excluded directory that
    sometimes holds first-party code
    (``provenance["vendored_excluded"]`` — e.g. tensorflow's
    ``third_party/xla``), and files that exceeded the size cap
    (``provenance["too_large"]`` — e.g. a large first-party test file,
    round-18's zed finding). Shared by ``dekko status``, ``map_status``,
    ``dekko summary``, and ``query``'s not-found/ambiguous replies so
    the wording is identical everywhere a caller might see it.

    Args:
        provenance: A map's provenance dict, or ``None``.

    Returns:
        E.g. ``"12 files unparsed — no parser for: astro (12)"``,
        every applicable note joined by a newline, or ``None`` when
        there is nothing to report.
    """
    if not provenance:
        return None
    parts: list[str] = []
    unsupported = provenance.get("unsupported")
    if unsupported:
        by_lang = unsupported.get("languages", {})
        detail = ", ".join(f"{lang} ({n})" for lang, n in by_lang.items())
        count = unsupported.get("count", 0)
        parts.append(f"{count} files unparsed — no parser for: {detail}")
    vendored = provenance.get("vendored_excluded")
    if vendored:
        by_dir = vendored.get("dirs", {})
        detail = ", ".join(f"{name} ({n})" for name, n in by_dir.items())
        count = vendored.get("count", 0)
        parts.append(
            f"{count} files under default-excluded directories "
            f"({detail}) were not mapped — pass --exclude '' or a "
            "narrower default-dir allowlist to include them if they "
            "hold first-party code"
        )
    too_large = provenance.get("too_large")
    if too_large:
        paths = too_large.get("paths", [])
        count = too_large.get("count", 0)
        detail = ", ".join(paths)
        hidden = count - len(paths)
        if hidden > 0:
            detail += f", +{hidden} more"
        parts.append(
            f"{count} file(s) exceeded the size cap and were not "
            f"mapped: {detail} — pass --max-file-size N to include "
            "them if they hold first-party code"
        )
    if not parts:
        return None
    return "\n  ".join(parts)


def compute_provenance(
    root: Path,
    paths: list[str],
    subpath: str | None,
    excludes: tuple[str, ...],
    max_file_size: int,
    graph: CallGraph,
    skipped: list[tuple[str, str]] | None = None,
) -> dict:
    """Build the provenance stamp for a freshly generated map.

    Args:
        root: Repository root that was mapped.
        paths: Repo-relative paths of every mapped file.
        subpath: Subtree restriction used for discovery, if any.
        excludes: Extra exclude globs used for discovery.
        max_file_size: Size cap used for discovery.
        graph: The resolved call graph, for stamping the repo-wide
            ambiguous-call rate so ``dekko doctor`` can read it without
            a full map load (see ``analysis/ambiguous.py``'s
            ``HIGH_AMBIGUOUS_RATE``).
        skipped: ``(path, reason)`` pairs from the same ``walker.
            discover`` call that produced ``paths``, used to record
            coverage notes for confirmed-unsupported languages, for
            files skipped only because they live under a
            default-excluded (vendored/build-output) directory, and
            for files that exceeded ``max_file_size``.

    Returns:
        JSON-serializable provenance dict.
    """
    denom = len(graph.edges) + len(graph.ambiguous)
    return {
        "tool_version": _pkg_version("dekko"),
        "spec_hash": spec_fingerprint(),
        "git_commit": _git_commit(root),
        "subpath": subpath,
        "excludes": list(excludes),
        "max_file_size": max_file_size,
        "files": {rel: _file_hash(root / rel) for rel in paths},
        "stat": {rel: _stat_sig(root / rel) for rel in paths},
        "unsupported": _unsupported_summary(skipped),
        "vendored_excluded": _vendored_summary(skipped),
        "too_large": _too_large_summary(skipped),
        "ambiguous_sites": len(graph.ambiguous),
        "ambiguous_rate": (
            round(len(graph.ambiguous) / denom, 4) if denom else 0.0
        ),
    }


def _git_commit(root: Path) -> str | None:
    """Return the HEAD commit of the repo at root, or ``None``."""
    try:
        proc = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if proc.returncode != 0:
        return None
    return proc.stdout.strip()


def _file_hash(path: Path) -> str:
    """Short content hash used for staleness comparison."""
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()[:16]
    except OSError:
        return "unreadable"


def _stat_sig(path: Path) -> list[int]:
    """``[mtime_ns, size]`` signature for the freshness fast path.

    Returns an empty list on error so it never matches a recorded
    signature, forcing a content hash for that file.
    """
    try:
        st = path.stat()
    except OSError:
        return []
    return [st.st_mtime_ns, st.st_size]


@dataclass
class MapIndex:
    """map.json loaded into lookup structures.

    Attributes:
        root_label: Display label of the mapped root.
        symbols_by_id: Symbol id → symbol.
        symbols_by_name: Bare name → symbols sharing it.
        symbols_by_qualname: Qualified name → symbols sharing it.
        symbols_by_path: File path → its symbols in definition order.
        calls_in: Symbol id → caller ids.
        calls_out: Symbol id → callee ids.
        edge_lines: ``(caller id, callee id)`` → call-site lines
            (empty for maps written before doc version 3).
        imports_by_path: File path → imports declared in it.
        type_aliases_by_path: File path → bare names of type-alias
            declarations in it (TS/TSX only, empty for maps written
            before doc version 10 — see ``model.FileMap.
            type_aliases``). Consulted by ``query.
            _heritage_external_label`` as a same-file counterpart to
            ``imports_by_path``'s cross-file relative-import check
            (round-19 claude-code finding: a same-file ``type X =
            {...}`` used in an ``implements``/``extends`` clause had
            no structural signal to distinguish it from a genuinely
            external base, since it's never extracted as a ``Symbol``
            at all).
        languages_by_path: File path → language name.
        docs_by_path: File path → module doc first line, or ``None``.
        errors_by_path: File path → parse error message (only files
            that failed to parse appear).
        externals_by_name: Base callee identifier → external calls
            referencing it (e.g. ``run`` for ``subprocess.run``).
        ambiguous_in: Candidate symbol id → ``(caller_id, name)`` pairs
            that could have resolved to it but didn't, because the
            name matched more than one repo-wide candidate. These
            never contribute to ``calls_in``/fan-in (see ``resolver``'s
            module docstring) — this is how a caller can tell "N more
            call sites exist but weren't resolvable to this symbol
            specifically" instead of reading a low fan-in as complete.
        ambiguous_out: Caller symbol id → names it called ambiguously
            (2+ repo-wide candidates, none disambiguated). The
            outgoing-side counterpart to ``ambiguous_in`` — these never
            contribute to ``calls_out`` either, so ``query callees``
            can disclose "N outgoing call(s) not counted here" the same
            way ``query callers`` already discloses ``ambiguous_in``
            (round-09 §2.1 part A).
        referenced_in: Symbol id → ids that reference it as a value
            (object-literal property, array element, call argument,
            assignment RHS) without calling it — e.g. a callback wired
            up by name (empty for maps written before doc version 4).
        referenced_out: Symbol id → ids it references as a value
            without calling them.
        ref_lines: ``(caller id, callee id)`` → reference-site lines
            for the ``referenced`` edge table (empty for maps written
            before doc version 4). Kept separate from ``edge_lines``
            rather than merged into it, since a caller can in
            principle both call and reference the same callee and a
            single dict keyed only on ``(caller, callee)`` would let
            one overwrite the other.
        heritage_out: Symbol id (subtype) → resolved supertype ids
            (empty for maps written before doc version 6).
        heritage_in: Symbol id (supertype) → resolved subtype ids.
        heritage_lines: ``(subtype id, supertype id)`` → clause-site
            lines, mirroring ``edge_lines``.
        heritage_relation: ``(subtype id, supertype id)`` → relation
            string (``"extends"``/``"implements"``/``"impl"``/
            ``"embeds"``) — needed since, like ``Edge``, a resolved
            ``HeritageEdge`` isn't kept as an object in the index,
            only its adjacency and this side table.
        heritage_ambiguous_in: Candidate (supertype) symbol id →
            ``(subtype_id, name)`` pairs that could have resolved to
            it but didn't — the heritage counterpart to
            ``ambiguous_in``.
        heritage_ambiguous_out: Subtype symbol id → supertype names it
            named ambiguously — the heritage counterpart to
            ``ambiguous_out``.
        heritage_external_out: Subtype symbol id → heritage clauses
            whose supertype is outside the repo. Caller(subtype)-
            indexed rather than name-indexed (unlike ``externals_by_
            name``'s "who calls this external name" shape) since
            ``query supertypes`` needs "what does *this* type's own
            heritage point at, including external bases" — a
            per-symbol lookup, not a repo-wide name search. This is a
            deliberate implementation deviation from the design doc's
            literal ``heritage_externals_by_name`` (name-indexed, the
            ``externals_by_name`` shape) — nothing in this design
            needs a name-indexed heritage-external search yet, and a
            caller-indexed table is what ``supertypes`` rendering
            actually requires; see the design doc's "Implementation
            notes" for the rationale.
        heritage_synthetic_tiebreak_count: Repo-wide count of resolved
            heritage edges that rest on the round-24 heritage
            crate-decoy tiebreak (``.features/plans/round24/
            03-heritage-crate-decoy-tiebreak.md``) rather than an
            unambiguous structural match — see
            ``model.CallGraph.heritage_synthetic_tiebreak_count``.
            ``0`` for maps written before doc version 11.
        module_deps_out: File path → sorted paths it imports (empty
            for maps written before doc version 7) — see
            ``resolver.resolve_imports``/``model.ModuleGraph``. Keyed
            and valued by file path, not symbol id, unlike every other
            adjacency table above.
        module_deps_in: File path → sorted paths that import it.
        module_edge_names: ``(importer path, imported path)`` → the
            local names imported across that edge, mirroring
            ``heritage_lines``'s side-table shape (an edge's own
            per-pair data not carried by the adjacency tables alone).
        module_external: File path → raw import-source strings that
            did not resolve to an in-repo file (stdlib/third-party/
            framework imports, or a source this pass couldn't
            confidently place) — the module-graph counterpart to
            ``externals_by_name``, but path-indexed rather than
            name-indexed, since ``deps --file`` needs "what did *this*
            file import that we couldn't resolve," not a repo-wide
            name search.
        throws_out: Symbol id (or module pseudo-id) → resolved
            raised-repo-type ids (empty for maps written before doc
            version 8) — Python/Java/C++/JS/TS only, see
            ``resolver.resolve_throws``/``model.ThrowEdge``.
        throws_lines: ``(caller, raised-type id)`` → throw-site lines,
            mirroring ``edge_lines``.
        throws_ambiguous_out: Caller id → raised-type names it named
            ambiguously — the throws counterpart to ``ambiguous_out``.
        throws_external_out: Caller id → throw sites whose raised type
            is outside the repo — the common case (most raised types
            are stdlib/third-party); caller-indexed, mirroring
            ``heritage_external_out``.
        throws_bare_out: Caller id → ``(path, line)`` pairs of bare
            re-raise sites (Python bare ``raise``, C++ bare ``throw;``)
            — kept separate since a re-raise's actual type isn't
            tracked (see ``model.CallGraph.throws_bare``).
        catches: Every except/catch clause across the repo, resolved
            (empty for maps written before doc version 8) — same
            Python/Java/C++/JS/TS scope as ``throws_out``. A
            ``dekko query catches Y`` request scans this list by name
            rather than through a resolved-id index (see
            ``model.CatchSite``'s docstring for why).
        env_reads_by_key: Literal env-var name → every read site
            naming it, repo-wide (empty for maps written before doc
            version 9) — see ``model.EnvRead``. Grouped by ``key``
            rather than caller-indexed like ``throws_out``/``catches``,
            since ``dekko query env NAME`` is a name lookup, not a
            per-symbol walk; ``--list`` iterates this dict directly for
            its "distinct keys by read-site count" ranking. No
            resolved/candidate-ladder shape needed — the literal key
            text is already the fully-resolved fact, so unlike every
            other new field this doc set's designs added, there is no
            corresponding `env_reads_ambiguous`/`env_reads_external`
            side table.
        notes: Symbol id → note texts loaded from ``.dekko/notes.json``.
        provenance: Provenance stamp, or ``None`` for v1 documents.
        doc_version: The on-disk document's ``"version"`` field (``1``
            for documents predating the field entirely), or
            ``MAP_DOC_VERSION`` for an index built in-process by
            ``index_from_maps`` rather than loaded from disk.
            ``repo_ops._map_run_is_noop`` reads this to tell "this
            repo's map.json is already in the current on-disk format"
            apart from "tool_version/spec_hash match but the format
            itself changed underneath them" (round-15 plan: a
            ``MAP_DOC_VERSION`` bump alone, with no package version
            bump, would otherwise be invisible to that no-op check).
    """

    root_label: str
    symbols_by_id: dict[str, Symbol] = field(default_factory=dict)
    symbols_by_name: dict[str, list[Symbol]] = field(default_factory=dict)
    symbols_by_qualname: dict[str, list[Symbol]] = field(default_factory=dict)
    symbols_by_path: dict[str, list[Symbol]] = field(default_factory=dict)
    calls_in: dict[str, list[str]] = field(default_factory=dict)
    calls_out: dict[str, list[str]] = field(default_factory=dict)
    edge_lines: dict[tuple[str, str], list[int]] = field(default_factory=dict)
    imports_by_path: dict[str, list[Import]] = field(default_factory=dict)
    type_aliases_by_path: dict[str, frozenset[str]] = field(
        default_factory=dict
    )
    languages_by_path: dict[str, str] = field(default_factory=dict)
    docs_by_path: dict[str, str | None] = field(default_factory=dict)
    errors_by_path: dict[str, str] = field(default_factory=dict)
    externals_by_name: dict[str, list[ExternalCall]] = field(
        default_factory=dict
    )
    ambiguous_in: dict[str, list[tuple[str, str]]] = field(
        default_factory=dict
    )
    ambiguous_out: dict[str, list[str]] = field(default_factory=dict)
    referenced_in: dict[str, list[str]] = field(default_factory=dict)
    referenced_out: dict[str, list[str]] = field(default_factory=dict)
    ref_lines: dict[tuple[str, str], list[int]] = field(default_factory=dict)
    heritage_out: dict[str, list[str]] = field(default_factory=dict)
    heritage_in: dict[str, list[str]] = field(default_factory=dict)
    heritage_lines: dict[tuple[str, str], list[int]] = field(
        default_factory=dict
    )
    heritage_relation: dict[tuple[str, str], str] = field(default_factory=dict)
    heritage_ambiguous_in: dict[str, list[tuple[str, str]]] = field(
        default_factory=dict
    )
    heritage_ambiguous_out: dict[str, list[str]] = field(default_factory=dict)
    heritage_external_out: dict[str, list[ExternalCall]] = field(
        default_factory=dict
    )
    heritage_synthetic_tiebreak_count: int = 0
    module_deps_out: dict[str, list[str]] = field(default_factory=dict)
    module_deps_in: dict[str, list[str]] = field(default_factory=dict)
    module_edge_names: dict[tuple[str, str], list[str]] = field(
        default_factory=dict
    )
    module_external: dict[str, list[str]] = field(default_factory=dict)
    throws_out: dict[str, list[str]] = field(default_factory=dict)
    throws_lines: dict[tuple[str, str], list[int]] = field(
        default_factory=dict
    )
    throws_ambiguous_out: dict[str, list[str]] = field(default_factory=dict)
    throws_external_out: dict[str, list[ExternalCall]] = field(
        default_factory=dict
    )
    throws_bare_out: dict[str, list[tuple[str, int]]] = field(
        default_factory=dict
    )
    catches: list[CatchSite] = field(default_factory=list)
    env_reads_by_key: dict[str, list[EnvRead]] = field(default_factory=dict)
    notes: dict[str, list[str]] = field(default_factory=dict)
    provenance: dict | None = None
    doc_version: int = MAP_DOC_VERSION

    def degree(self, sym_id: str) -> int:
        """Total fan-in + fan-out of a symbol id."""
        return len(self.calls_in.get(sym_id, [])) + len(
            self.calls_out.get(sym_id, [])
        )

    def without_tests(self) -> "MapIndex":
        """A filtered view with all test code removed.

        Drops symbols classified as test code, edges touching them
        (including module-level test callers), and external calls made
        from test files. A symbol is dropped when either its file path
        is a test path (``classify.is_test_path``, works even on
        pre-v3 documents that lack the ``test`` flag) or the extractor
        set ``Symbol.test`` (path-based classification plus
        language-specific containers such as Rust's inline
        ``mod tests { ... }``).

        Returns:
            A new ``MapIndex``; ``self`` is left untouched.
        """
        out = MapIndex(
            root_label=self.root_label,
            provenance=self.provenance,
            doc_version=self.doc_version,
        )
        for sid, sym in self.symbols_by_id.items():
            if _symbol_is_test(sym):
                continue
            out.symbols_by_id[sid] = sym
            out.symbols_by_name.setdefault(sym.name, []).append(sym)
            out.symbols_by_qualname.setdefault(sym.qualname, []).append(sym)
            out.symbols_by_path.setdefault(sym.path, []).append(sym)
        by_id = self.symbols_by_id
        out.calls_in = _filter_adjacency(self.calls_in, by_id)
        out.calls_out = _filter_adjacency(self.calls_out, by_id)
        out.edge_lines = {
            key: lines
            for key, lines in self.edge_lines.items()
            if _prod_id(key[0], by_id) and _prod_id(key[1], by_id)
        }
        out.imports_by_path = _filter_paths(self.imports_by_path)
        out.type_aliases_by_path = _filter_paths(self.type_aliases_by_path)
        out.languages_by_path = _filter_paths(self.languages_by_path)
        out.docs_by_path = _filter_paths(self.docs_by_path)
        out.errors_by_path = _filter_paths(self.errors_by_path)
        out.notes = {
            sid: texts
            for sid, texts in self.notes.items()
            if _prod_id(sid, by_id)
        }
        for name, exts in self.externals_by_name.items():
            kept = [e for e in exts if _prod_id(e.caller, by_id)]
            if kept:
                out.externals_by_name[name] = kept
        for cand, pairs in self.ambiguous_in.items():
            if not _prod_id(cand, by_id):
                continue
            kept_pairs = [
                (caller, name)
                for caller, name in pairs
                if _prod_id(caller, by_id)
            ]
            if kept_pairs:
                out.ambiguous_in[cand] = kept_pairs
        out.ambiguous_out = {
            caller: names
            for caller, names in self.ambiguous_out.items()
            if _prod_id(caller, by_id)
        }
        out.referenced_in = _filter_adjacency(self.referenced_in, by_id)
        out.referenced_out = _filter_adjacency(self.referenced_out, by_id)
        out.ref_lines = {
            key: lines
            for key, lines in self.ref_lines.items()
            if _prod_id(key[0], by_id) and _prod_id(key[1], by_id)
        }
        _filter_heritage(self, out, by_id)
        _filter_module_graph(self, out)
        _filter_throws_catches(self, out, by_id)
        _filter_env_reads(self, out)
        return out


def _symbol_is_test(sym: Symbol) -> bool:
    """Whether a symbol is test code, by path or extractor flag.

    Two independent signals can mark test code: the defining file's
    path (``classify.is_test_path``) and the extractor's per-symbol
    ``Symbol.test`` flag (path-based classification plus
    language-specific containers such as Rust's inline
    ``mod tests { ... }`` — see ``Symbol.test``'s docstring). Either
    one is sufficient; this is the single place both are combined so
    ``without_tests()`` actually excludes everything ``Symbol.test``
    flags, not just what the path alone would catch.
    """
    return sym.test or is_test_path(sym.path)


def _prod_id(sym_or_module_id: str, symbols_by_id: dict[str, Symbol]) -> bool:
    """Whether a symbol/module id belongs to production (non-test) code.

    Resolves the id against ``symbols_by_id`` and defers to
    ``_symbol_is_test`` when it names a real symbol. Ids that don't
    resolve (module-level pseudo-callers, ``path::<module>``, which
    are never entered into ``symbols_by_id``) fall back to a
    path-only check.
    """
    sym = symbols_by_id.get(sym_or_module_id)
    if sym is not None:
        return not _symbol_is_test(sym)
    return not is_test_path(sym_or_module_id.split("::", 1)[0])


def _filter_adjacency(
    table: dict[str, list[str]], symbols_by_id: dict[str, Symbol]
) -> dict[str, list[str]]:
    """Drop test-path nodes from an adjacency table, keys and values."""
    out: dict[str, list[str]] = {}
    for sid, others in table.items():
        if not _prod_id(sid, symbols_by_id):
            continue
        kept = [o for o in others if _prod_id(o, symbols_by_id)]
        if kept:
            out[sid] = kept
    return out


def _filter_paths(mapping: dict) -> dict:
    """Drop test-path keys from a path-keyed mapping."""
    return {
        path: value
        for path, value in mapping.items()
        if not is_test_path(path)
    }


def _filter_heritage(
    src: "MapIndex", out: "MapIndex", by_id: dict[str, Symbol]
) -> None:
    """Fill ``out``'s heritage fields from ``src``, test code dropped.

    Split out of ``MapIndex.without_tests`` purely to keep that
    method's cyclomatic complexity under the project's Ruff limit —
    behaviorally this is still part of the same filtered-view build,
    mirroring the ``ambiguous_in``/``ambiguous_out`` filter block
    immediately above it in ``without_tests`` line for line, just for
    the heritage-graph fields instead of the call-graph ones.
    """
    out.heritage_out = _filter_adjacency(src.heritage_out, by_id)
    out.heritage_in = _filter_adjacency(src.heritage_in, by_id)
    out.heritage_lines = {
        key: lines
        for key, lines in src.heritage_lines.items()
        if _prod_id(key[0], by_id) and _prod_id(key[1], by_id)
    }
    out.heritage_relation = {
        key: rel
        for key, rel in src.heritage_relation.items()
        if _prod_id(key[0], by_id) and _prod_id(key[1], by_id)
    }
    for cand, pairs in src.heritage_ambiguous_in.items():
        if not _prod_id(cand, by_id):
            continue
        kept_pairs = [
            (subtype, name)
            for subtype, name in pairs
            if _prod_id(subtype, by_id)
        ]
        if kept_pairs:
            out.heritage_ambiguous_in[cand] = kept_pairs
    out.heritage_ambiguous_out = {
        subtype: names
        for subtype, names in src.heritage_ambiguous_out.items()
        if _prod_id(subtype, by_id)
    }
    for subtype, exts in src.heritage_external_out.items():
        if _prod_id(subtype, by_id):
            out.heritage_external_out[subtype] = exts
    # Repo-wide scalar, not per-symbol -- carried over unfiltered,
    # same as every other whole-repo count this view doesn't narrow.
    out.heritage_synthetic_tiebreak_count = (
        src.heritage_synthetic_tiebreak_count
    )


def _filter_module_graph(src: "MapIndex", out: "MapIndex") -> None:
    """Fill ``out``'s module-graph fields from ``src``, test paths
    dropped.

    Unlike ``_filter_heritage``/``_filter_adjacency``, the module
    graph is keyed and valued by file *path* directly (not a symbol
    id needing a ``symbols_by_id`` lookup to classify), so this
    filters on ``is_test_path`` alone rather than via ``_prod_id``.
    """
    for path, others in src.module_deps_out.items():
        if is_test_path(path):
            continue
        kept = [o for o in others if not is_test_path(o)]
        if kept:
            out.module_deps_out[path] = kept
    for path, others in src.module_deps_in.items():
        if is_test_path(path):
            continue
        kept = [o for o in others if not is_test_path(o)]
        if kept:
            out.module_deps_in[path] = kept
    out.module_edge_names = {
        key: names
        for key, names in src.module_edge_names.items()
        if not is_test_path(key[0]) and not is_test_path(key[1])
    }
    out.module_external = {
        path: sources
        for path, sources in src.module_external.items()
        if not is_test_path(path)
    }


def _filter_throws_catches(
    src: "MapIndex", out: "MapIndex", by_id: dict[str, Symbol]
) -> None:
    """Fill ``out``'s throws/catches fields from ``src``, test code
    dropped.

    Split out of ``MapIndex.without_tests`` for the same reason
    ``_filter_heritage``/``_filter_module_graph`` are. ``catches`` is a
    flat per-clause list (not an adjacency table), so it's filtered by
    a direct ``_prod_id`` check on each site's ``caller`` rather than
    via ``_filter_adjacency``.
    """
    out.throws_out = _filter_adjacency(src.throws_out, by_id)
    out.throws_lines = {
        key: lines
        for key, lines in src.throws_lines.items()
        if _prod_id(key[0], by_id) and _prod_id(key[1], by_id)
    }
    out.throws_ambiguous_out = {
        caller: names
        for caller, names in src.throws_ambiguous_out.items()
        if _prod_id(caller, by_id)
    }
    for caller, exts in src.throws_external_out.items():
        if _prod_id(caller, by_id):
            out.throws_external_out[caller] = exts
    for caller, sites in src.throws_bare_out.items():
        if _prod_id(caller, by_id):
            out.throws_bare_out[caller] = sites
    out.catches = [c for c in src.catches if _prod_id(c.caller, by_id)]


def _filter_env_reads(src: "MapIndex", out: "MapIndex") -> None:
    """Fill ``out.env_reads_by_key`` from ``src``, test-path reads
    dropped.

    Filtered on ``EnvRead.path`` directly (mirrors
    ``_filter_module_graph``'s path-keyed filtering), not via
    ``_prod_id`` — an ``EnvRead``'s ``caller_id`` is disclosure-only
    (see ``model.EnvRead``'s docstring), not something ``dekko query
    env`` looks up by id, so there's no adjacency table here requiring
    symbol-level classification the way ``_filter_throws_catches``
    needs.
    """
    for key, reads in src.env_reads_by_key.items():
        kept = [r for r in reads if not is_test_path(r.path)]
        if kept:
            out.env_reads_by_key[key] = kept


@dataclass
class Freshness:
    """Result of comparing a map's provenance to the working tree.

    Attributes:
        reason: ``None`` when fresh; otherwise ``"missing"`` (no
            provenance at all — a pre-v2 map), ``"version"`` (the map
            predates the running dekko build — its ``tool_version``
            or ``spec_hash`` no longer matches, so ``added``/
            ``removed``/``changed`` are not computed), or ``"content"``
            (source files were added, changed, or removed).
        version_stale: True when the map's recorded ``tool_version``
            differs from the running process's own installed version.
            Only meaningful when ``reason == "version"``.
        spec_stale: True when the map's recorded ``spec_hash`` differs
            from what the running process's currently-loaded
            extraction specs would produce — the case a long-lived
            process (``dekko serve``) can hit silently, since a
            reinstall underneath it doesn't change ``tool_version``
            every release, so ``version_stale`` alone can read
            "identical" while the process is still running stale
            extractor code (round-09 §2.3: a ``dekko serve`` reported
            stale with ``built by dekko 0.21.3, running 0.21.3`` — the
            same string on both sides — with nothing distinguishing
            which check actually fired). Only meaningful when
            ``reason == "version"``.
        built_version: The map's recorded ``tool_version``, or
            ``None`` unless ``reason == "version"``.
        running_version: The checking process's own installed
            version, or ``None`` unless ``reason == "version"``.
        built_spec_hash: The map's recorded ``spec_hash``, or ``None``
            unless ``reason == "version"``.
        running_spec_hash: The checking process's own computed
            ``languages.spec_fingerprint()``, or ``None`` unless
            ``reason == "version"``.
    """

    fresh: bool
    added: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    changed: list[str] = field(default_factory=list)
    reason: str | None = None
    version_stale: bool = False
    spec_stale: bool = False
    built_version: str | None = None
    running_version: str | None = None
    built_spec_hash: str | None = None
    running_spec_hash: str | None = None


def describe_version_stale(fresh: Freshness) -> str:
    """Name which staleness signal(s) fired for a "version" verdict.

    ``Freshness.reason == "version"`` collapses two independent
    signals (``tool_version`` mismatch, ``spec_hash`` mismatch) into
    one string. A long-lived ``dekko serve`` process can have an
    identical ``tool_version`` on both sides — Python doesn't hot-
    reload already-imported modules, so a ``uv tool install
    --reinstall`` after the server started has no effect on that
    process's own ``spec_fingerprint()`` output until it restarts —
    which used to read as a self-contradictory "built by dekko 0.21.3,
    running 0.21.3" with no explanation of what was actually stale
    (round-09 §2.3). This names the differentiator explicitly using
    the raw values already carried on ``fresh``, with no
    surface-specific actionable suffix — callers (CLI, MCP, doctor)
    each append their own suggested next step.

    Args:
        fresh: A freshness verdict with ``reason == "version"``.

    Returns:
        A one-line ``"stale (...)"`` prefix naming which signal(s)
        fired and their built-vs-running values.
    """
    which = "+".join(
        name
        for name, stale in (
            ("version", fresh.version_stale),
            ("spec_hash", fresh.spec_stale),
        )
        if stale
    )
    parts: list[str] = []
    if fresh.version_stale:
        parts.append(
            f"tool_version: built by dekko {fresh.built_version}, "
            f"running {fresh.running_version}"
        )
    if fresh.spec_stale:
        built_hash = (fresh.built_spec_hash or "unknown")[:12]
        running_hash = (fresh.running_spec_hash or "unknown")[:12]
        spec_detail = (
            f"spec_hash: map built with extractor spec {built_hash}, "
            f"this process is running spec {running_hash}"
        )
        if not fresh.version_stale:
            spec_detail += (
                f" (same version string {fresh.running_version} on "
                "both sides — this is a long-lived process running "
                "older/different extractor code than what's on disk; "
                "restart it)"
            )
        parts.append(spec_detail)
    return f"stale ({which}): " + "; ".join(parts)


def _symbol_from_dict(d: dict) -> Symbol:
    """Rebuild a ``Symbol`` (with ``Param``s) from its JSON dict."""
    params = [Param(**p) for p in d.get("params", [])]
    return Symbol(
        id=d["id"],
        name=d["name"],
        qualname=d["qualname"],
        kind=d["kind"],
        path=d["path"],
        language=d["language"],
        params=params,
        returns=d.get("returns"),
        start_line=d.get("start_line", 0),
        end_line=d.get("end_line", 0),
        decorated=d.get("decorated", False),
        exported=d.get("exported", False),
        doc=d.get("doc"),
        test=d.get("test", False),
    )


def _load_notes(root: Path) -> dict[str, list[str]]:
    """Read ``.dekko/notes.json`` into symbol id → note texts.

    Read inline (rather than via the ``notes`` module) to keep this
    low-level loader free of higher-level imports.
    """
    try:
        doc = json.loads(
            (root / _MAP_DIR / "notes.json").read_text(encoding="utf-8")
        )
    except (OSError, json.JSONDecodeError):
        return {}
    raw = doc.get("notes")
    if not isinstance(raw, dict):
        return {}
    return {
        sym_id: [r.get("text", "") for r in records]
        for sym_id, records in raw.items()
    }


def _callee_base(text: str) -> str:
    """Base identifier of an external callee text.

    ``subprocess.run`` → ``run``; ``a::b`` → ``b``; ``Path`` → ``Path``.
    """
    parts = [p for p in _BASE_SPLIT.split(text) if p]
    return parts[-1] if parts else ""


def _check_doc_version(doc_version: object) -> int:
    """Validate a ``map.json`` document's ``"version"`` field.

    Args:
        doc_version: The raw ``doc.get("version", 1)`` value.

    Returns:
        ``doc_version``, narrowed to ``int``, when it's valid and not
        newer than ``MAP_DOC_VERSION``.

    Raises:
        MapFormatInvalidError: ``doc_version`` isn't an ``int``
            (``null``, a string, a float, a ``bool``, ...).
        MapFormatTooNewError: ``doc_version`` is a valid integer but
            greater than ``MAP_DOC_VERSION``.
    """
    if not isinstance(doc_version, int) or isinstance(doc_version, bool):
        raise MapFormatInvalidError(
            f'map.json has a malformed "version" field '
            f"({doc_version!r}); expected an integer. The file may "
            "be corrupted or truncated. Regenerate it with "
            "`dekko map`."
        )
    if doc_version > MAP_DOC_VERSION:
        raise MapFormatTooNewError(
            f"map.json is doc-version {doc_version}, newer than this "
            f"dekko build understands (max {MAP_DOC_VERSION}). "
            "Upgrade dekko, or if this is a long-lived process "
            "(dekko serve --mcp, or the dekko daemon), restart it to "
            "pick up the current version."
        )
    return doc_version


def load_map(root: Path) -> MapIndex | None:
    """Load ``root/.dekko/map.json`` into a ``MapIndex``.

    Args:
        root: Repository root whose ``.dekko/map.json`` should be read.

    Returns:
        The index, or ``None`` if the file is missing or unparsable.

    Raises:
        MapFormatTooNewError: The document's ``"version"`` is newer
            than ``MAP_DOC_VERSION`` — this process's parsing code
            predates the format and cannot safely interpret it (see
            the exception's docstring). Deliberately *not* folded into
            the "unparsable → ``None``" contract above: returning
            ``None`` here would read as "no map exists yet" to
            callers such as ``repo_ops.load_or_regen``, which would
            then regenerate and silently overwrite a perfectly good,
            newer-format ``map.json`` with this stale process's
            older-format output.
        MapFormatInvalidError: The document's ``"version"`` field is
            present but not an integer (``null``, a string, a float,
            ...) — the document is malformed or corrupted rather than
            merely newer (see the exception's docstring). Also
            deliberately not folded into the ``None`` contract, for
            the same reason as ``MapFormatTooNewError`` above.
    """
    path = root / _MAP_DIR / "map.json"
    try:
        doc = _json_loads(path.read_bytes())
    except (OSError, ValueError):
        return None

    doc_version = _check_doc_version(doc.get("version", 1))

    index = MapIndex(
        root_label=doc.get("root", root.name),
        provenance=doc.get("provenance"),
        notes=_load_notes(root),
        doc_version=doc_version,
    )
    for entry in doc.get("files", []):
        fpath = entry["path"]
        index.languages_by_path[fpath] = entry.get("language", "")
        index.docs_by_path[fpath] = entry.get("doc")
        if entry.get("error"):
            index.errors_by_path[fpath] = entry["error"]
        index.imports_by_path[fpath] = [
            Import(**imp) for imp in entry.get("imports", [])
        ]
        index.type_aliases_by_path[fpath] = frozenset(
            entry.get("type_aliases", [])
        )
    for d in doc.get("symbols", []):
        sym = _symbol_from_dict(d)
        index.symbols_by_id[sym.id] = sym
        index.symbols_by_name.setdefault(sym.name, []).append(sym)
        index.symbols_by_qualname.setdefault(sym.qualname, []).append(sym)
        index.symbols_by_path.setdefault(sym.path, []).append(sym)

    # v5+ documents intern caller/callee/candidate id strings into a
    # top-level "ids" table and reference them by integer index below
    # (round-15 plan); pre-v5 documents wrote those ids as raw strings
    # directly. `_resolve_ref` is a no-op passthrough for the latter,
    # so every loop below reads either shape unchanged.
    doc_ids = doc.get("ids")
    ids = (
        doc_ids
        if index.doc_version >= 5 and isinstance(doc_ids, list)
        else None
    )

    for edge in doc.get("edges", []):
        caller = _resolve_ref(edge["caller"], ids)
        callee = _resolve_ref(edge["callee"], ids)
        index.calls_out.setdefault(caller, []).append(callee)
        index.calls_in.setdefault(callee, []).append(caller)
        index.edge_lines[(caller, callee)] = edge.get("lines", [])
    for d in doc.get("external", []):
        ext = ExternalCall(
            caller=_resolve_ref(d.get("caller"), ids),
            callee=_resolve_ref(d.get("callee", ""), ids),
            lines=d.get("lines", []),
        )
        base = _callee_base(ext.callee)
        if base:
            index.externals_by_name.setdefault(base, []).append(ext)
    index.ambiguous_in, index.ambiguous_out = _index_ambiguous(
        (
            _resolve_ref(d.get("caller", ""), ids),
            d.get("name", ""),
            [_resolve_ref(c, ids) for c in d.get("candidates", [])],
        )
        for d in doc.get("ambiguous", [])
    )
    for edge in doc.get("referenced", []):
        caller = _resolve_ref(edge["caller"], ids)
        callee = _resolve_ref(edge["callee"], ids)
        index.referenced_out.setdefault(caller, []).append(callee)
        index.referenced_in.setdefault(callee, []).append(caller)
        index.ref_lines[(caller, callee)] = edge.get("lines", [])
    _load_heritage(index, doc, ids)
    _load_module_graph(index, doc, ids)
    _load_throws_catches(index, doc, ids)
    _load_env_reads(index, doc)
    return index


def _load_heritage(index: MapIndex, doc: dict, ids: list[str] | None) -> None:
    """Fill ``index``'s heritage fields from a parsed ``map.json`` doc.

    Split out of ``load_map`` purely to keep that function's
    cyclomatic complexity under the project's Ruff limit — behaviorally
    this is still part of the same document-load pass, mirroring the
    ``"referenced"`` loading block immediately above it in ``load_map``
    line for line, just for the ``"heritage"``/``"heritage_ambiguous"``/
    ``"heritage_external"`` sections instead. Absent entirely from
    documents written before doc version 6 — the ``.get(..., [])``
    defaults make every loop here a no-op for those, the same
    graceful-degradation contract every other v-gated section in
    ``load_map`` already has.
    """
    for edge in doc.get("heritage", []):
        subtype = _resolve_ref(edge["subtype"], ids)
        supertype = _resolve_ref(edge["supertype"], ids)
        index.heritage_out.setdefault(subtype, []).append(supertype)
        index.heritage_in.setdefault(supertype, []).append(subtype)
        index.heritage_lines[(subtype, supertype)] = edge.get("lines", [])
        index.heritage_relation[(subtype, supertype)] = edge.get(
            "relation", "extends"
        )
    index.heritage_ambiguous_in, index.heritage_ambiguous_out = (
        _index_ambiguous(
            (
                _resolve_ref(d.get("subtype", ""), ids),
                d.get("name", ""),
                [_resolve_ref(c, ids) for c in d.get("candidates", [])],
            )
            for d in doc.get("heritage_ambiguous", [])
        )
    )
    for d in doc.get("heritage_external", []):
        ext = ExternalCall(
            caller=_resolve_ref(d.get("caller"), ids),
            callee=_resolve_ref(d.get("callee", ""), ids),
            lines=d.get("lines", []),
        )
        index.heritage_external_out.setdefault(ext.caller, []).append(ext)
    index.heritage_synthetic_tiebreak_count = doc.get(
        "heritage_synthetic_tiebreak_count", 0
    )


def _load_module_graph(
    index: MapIndex, doc: dict, ids: list[str] | None
) -> None:
    """Fill ``index``'s module-graph fields from a parsed ``map.json``
    document.

    ``deps_out``/``deps_in`` are derived here from the ``"module_
    graph"."edges"`` list, mirroring how ``_load_heritage`` derives
    ``heritage_out``/``heritage_in`` from ``"heritage"`` rather than
    storing the adjacency redundantly on disk. Absent entirely from
    documents written before doc version 7 — ``.get(...)`` defaults
    make every loop here a no-op for those.
    """
    mg = doc.get("module_graph") or {}
    for edge in mg.get("edges", []):
        importer = _resolve_ref(edge["importer"], ids)
        imported = _resolve_ref(edge["imported"], ids)
        index.module_deps_out.setdefault(importer, []).append(imported)
        index.module_deps_in.setdefault(imported, []).append(importer)
        index.module_edge_names[(importer, imported)] = edge.get("names", [])
    for table in (index.module_deps_out, index.module_deps_in):
        for key in table:
            table[key] = sorted(set(table[key]))
    for entry in mg.get("external", []):
        path = _resolve_ref(entry["path"], ids)
        index.module_external.setdefault(path, []).extend(
            entry.get("sources", [])
        )


def _load_throws_catches(
    index: MapIndex, doc: dict, ids: list[str] | None
) -> None:
    """Fill ``index``'s throws/catches fields from a parsed ``map.json``
    document.

    Split out of ``load_map`` for the same reason ``_load_heritage``/
    ``_load_module_graph`` are. Absent entirely from documents written
    before doc version 8 — ``.get(..., [])`` defaults make every loop
    here a no-op for those.
    """
    for edge in doc.get("throws", []):
        caller = _resolve_ref(edge["caller"], ids)
        type_id = _resolve_ref(edge["type"], ids)
        index.throws_out.setdefault(caller, []).append(type_id)
        index.throws_lines[(caller, type_id)] = edge.get("lines", [])
    for key in index.throws_out:
        index.throws_out[key] = sorted(set(index.throws_out[key]))
    for d in doc.get("throws_ambiguous", []):
        caller = _resolve_ref(d.get("caller", ""), ids)
        name = d.get("name", "")
        if caller and name:
            index.throws_ambiguous_out.setdefault(caller, []).append(name)
    for d in doc.get("throws_external", []):
        ext = ExternalCall(
            caller=_resolve_ref(d.get("caller"), ids),
            callee=_resolve_ref(d.get("callee", ""), ids),
            lines=d.get("lines", []),
        )
        index.throws_external_out.setdefault(ext.caller, []).append(ext)
    for d in doc.get("throws_bare", []):
        caller = _resolve_ref(d.get("caller", ""), ids)
        index.throws_bare_out.setdefault(caller, []).append(
            (d.get("path", ""), d.get("line", 0))
        )
    for d in doc.get("catches", []):
        index.catches.append(
            CatchSite(
                caller=_resolve_ref(d.get("caller", ""), ids),
                path=d.get("path", ""),
                type_names=d.get("type_names", []),
                repo_types={
                    name: _resolve_ref(type_id, ids)
                    for name, type_id in d.get("repo_types", {}).items()
                },
                bare=d.get("bare", False),
                line=d.get("line", 0),
            )
        )


def _load_env_reads(index: MapIndex, doc: dict) -> None:
    """Fill ``index.env_reads_by_key`` from a parsed ``map.json`` doc.

    Split out of ``load_map`` for the same reason ``_load_heritage``/
    ``_load_module_graph``/``_load_throws_catches`` are. Absent
    entirely from documents written before doc version 9 —
    ``.get("env_reads", [])`` defaults make this a no-op for those.
    No id table involved here (unlike every ``_load_*`` sibling above)
    — ``caller_id`` is written and read as a plain string or ``null``,
    not routed through the shared ``ids`` intern table (see
    ``model.EnvRead``'s docstring: no resolution pass populates this
    field, so there's nothing to resolve on read either).
    """
    for d in doc.get("env_reads", []):
        read = EnvRead(
            caller_id=d.get("caller_id"),
            path=d.get("path", ""),
            key=d.get("key", ""),
            call=d.get("call", ""),
            line=d.get("line", 0),
        )
        index.env_reads_by_key.setdefault(read.key, []).append(read)


def _index_ambiguous(
    entries: Iterator[tuple[str, str, list[str]]],
) -> tuple[dict[str, list[tuple[str, str]]], dict[str, list[str]]]:
    """Index ambiguous-call records by candidate, and by caller.

    An ambiguous call never becomes a resolved edge (see ``resolver``'s
    module docstring), so it never shows up in either side's
    ``calls_in``/``calls_out``. This builds both read-side views in
    one pass over the same records:

    - ``ambiguous_in``: for each candidate a name collision could have
      pointed at, who tried and under what name — so a low fan-in can
      be qualified as "+N ambiguous call sites not counted" instead of
      read as exhaustive.
    - ``ambiguous_out``: for each caller, the names it called
      ambiguously — the outgoing-side counterpart, so ``query
      callees`` can disclose the same kind of gap ``query callers``
      already discloses via ``ambiguous_in`` (round-09 §2.1 part A).

    Args:
        entries: ``(caller_id, name, candidate_ids)`` triples.

    Returns:
        ``(ambiguous_in, ambiguous_out)``.
    """
    ambiguous_in: dict[str, list[tuple[str, str]]] = {}
    ambiguous_out: dict[str, list[str]] = {}
    for caller, name, candidates in entries:
        if candidates:
            ambiguous_out.setdefault(caller, []).append(name)
        for cand in candidates:
            ambiguous_in.setdefault(cand, []).append((caller, name))
    return ambiguous_in, ambiguous_out


def index_from_maps(
    files: list[FileMap], graph: CallGraph, root_label: str
) -> MapIndex:
    """Build a ``MapIndex`` from in-memory extraction results.

    The in-process counterpart to ``load_map``: it produces the same
    index the read commands get from ``map.json``, so MAP.md rendering
    can reuse the ``summary``/``stats`` computations at generation time
    without a round trip through disk. Notes are not loaded — the
    overview describes structure, not annotations.

    Args:
        files: Per-file extraction results.
        graph: Resolved call graph.
        root_label: Display label of the mapped root.

    Returns:
        A populated ``MapIndex``.
    """
    index = MapIndex(root_label=root_label)
    for fm in files:
        index.languages_by_path[fm.path] = fm.language
        index.docs_by_path[fm.path] = fm.doc
        if fm.error:
            index.errors_by_path[fm.path] = fm.error
        index.imports_by_path[fm.path] = list(fm.imports)
        index.type_aliases_by_path[fm.path] = frozenset(fm.type_aliases)
        for sym in fm.symbols:
            index.symbols_by_id[sym.id] = sym
            index.symbols_by_name.setdefault(sym.name, []).append(sym)
            index.symbols_by_qualname.setdefault(sym.qualname, []).append(sym)
            index.symbols_by_path.setdefault(sym.path, []).append(sym)
    for edge in graph.edges:
        index.calls_out.setdefault(edge.caller, []).append(edge.callee)
        index.calls_in.setdefault(edge.callee, []).append(edge.caller)
        index.edge_lines[(edge.caller, edge.callee)] = edge.lines
    for ext in graph.external:
        base = _callee_base(ext.callee)
        if base:
            index.externals_by_name.setdefault(base, []).append(ext)
    index.ambiguous_in, index.ambiguous_out = _index_ambiguous(
        iter(graph.ambiguous)
    )
    for edge in graph.referenced:
        index.referenced_out.setdefault(edge.caller, []).append(edge.callee)
        index.referenced_in.setdefault(edge.callee, []).append(edge.caller)
        index.ref_lines[(edge.caller, edge.callee)] = edge.lines
    for edge in graph.heritage:
        index.heritage_out.setdefault(edge.subtype, []).append(edge.supertype)
        index.heritage_in.setdefault(edge.supertype, []).append(edge.subtype)
        index.heritage_lines[(edge.subtype, edge.supertype)] = edge.lines
        index.heritage_relation[(edge.subtype, edge.supertype)] = edge.relation
    index.heritage_ambiguous_in, index.heritage_ambiguous_out = (
        _index_ambiguous(iter(graph.heritage_ambiguous))
    )
    for ext in graph.heritage_external:
        index.heritage_external_out.setdefault(ext.caller, []).append(ext)
    index.heritage_synthetic_tiebreak_count = (
        graph.heritage_synthetic_tiebreak_count
    )
    _index_module_graph(index, graph)
    _index_throws_catches(index, graph)
    _index_env_reads(index, graph)
    return index


def _index_module_graph(index: MapIndex, graph: CallGraph) -> None:
    """The ``index_from_maps`` fill-in loop for the module graph.

    Split out of ``index_from_maps`` purely to keep that function's
    cyclomatic complexity under the project's Ruff limit — behaviorally
    this is still part of the same in-process index build, mirroring
    ``_load_module_graph``'s on-disk-read counterpart.
    """
    for edge in graph.modules.edges:
        index.module_deps_out.setdefault(edge.importer, []).append(
            edge.imported
        )
        index.module_deps_in.setdefault(edge.imported, []).append(
            edge.importer
        )
        index.module_edge_names[(edge.importer, edge.imported)] = edge.names
    for table in (index.module_deps_out, index.module_deps_in):
        for key in table:
            table[key] = sorted(set(table[key]))
    for path, sources in graph.modules.external.items():
        index.module_external[path] = sources


def _index_throws_catches(index: MapIndex, graph: CallGraph) -> None:
    """The ``index_from_maps`` fill-in loop for throws/catches.

    Split out of ``index_from_maps`` for the same reason
    ``_index_module_graph`` is, mirroring ``_load_throws_catches``'s
    on-disk-read counterpart.
    """
    for edge in graph.throws:
        index.throws_out.setdefault(edge.caller, []).append(edge.type)
        index.throws_lines[(edge.caller, edge.type)] = edge.lines
    for key in index.throws_out:
        index.throws_out[key] = sorted(set(index.throws_out[key]))
    for caller, name, _cands in graph.throws_ambiguous:
        index.throws_ambiguous_out.setdefault(caller, []).append(name)
    for ext in graph.throws_external:
        index.throws_external_out.setdefault(ext.caller, []).append(ext)
    for caller, path, line in graph.throws_bare:
        index.throws_bare_out.setdefault(caller, []).append((path, line))
    index.catches = list(graph.catches)


def _index_env_reads(index: MapIndex, graph: CallGraph) -> None:
    """The ``index_from_maps`` fill-in loop for env-var reads.

    Split out for the same reason ``_index_module_graph``/``_index_
    throws_catches`` are. A plain grouping pass, not a mirror of
    ``_load_env_reads``'s id-resolution shape — no resolution or
    symbol-id lookup is needed (see ``model.EnvRead``'s docstring).
    """
    for read in graph.env_reads:
        index.env_reads_by_key.setdefault(read.key, []).append(read)


def check_freshness(root: Path, index: MapIndex) -> Freshness:
    """Compare an index's provenance against the current tree.

    Discovery re-runs with the options recorded in the provenance so
    subtree or filtered maps are judged on their own terms. Maps
    without provenance (v1 documents) are always stale.

    Args:
        root: Repository root.
        index: Loaded map index.

    Returns:
        Freshness verdict with per-file difference lists.
    """
    if not index.provenance:
        return Freshness(
            fresh=False,
            changed=sorted(index.symbols_by_path),
            reason="missing",
        )
    return _freshness_from_provenance(root, index.provenance)


def check_freshness_provenance(
    root: Path, provenance: dict | None
) -> Freshness:
    """Cheap freshness check driven by a provenance dict alone.

    Same comparison as ``check_freshness``, for callers that only have
    the provenance sidecar (``load_provenance``) rather than a full
    ``MapIndex`` — e.g. ``dekko status``, which has no other use for
    the parsed symbol/call graph. The one behavioral difference: a
    missing-provenance verdict here can't list every symbol as
    ``changed`` the way ``check_freshness(root, index)`` can, since
    that needs the full symbol table this path never builds. A caller
    that needs that detail on a ``provenance is None`` result should
    fall back to ``check_freshness(root, load_map(root))``.

    Args:
        root: Repository root.
        provenance: Provenance dict from ``load_provenance``, or
            ``None``.

    Returns:
        Freshness verdict; ``changed`` is empty (not exhaustive) when
        ``provenance`` is ``None``.
    """
    if not provenance:
        return Freshness(fresh=False, reason="missing")
    return _freshness_from_provenance(root, provenance)


def _freshness_from_provenance(root: Path, prov: dict) -> Freshness:
    """Shared comparison body for both freshness-check entry points."""
    built_version = prov.get("tool_version")
    running_version = _pkg_version("dekko")
    built_spec_hash = prov.get("spec_hash")
    running_spec_hash = spec_fingerprint()
    version_stale = built_version != running_version
    spec_stale = built_spec_hash != running_spec_hash
    if version_stale or spec_stale:
        # The map was built by a different dekko (or an unreleased
        # extractor change under the same version string). Source
        # content may be byte-identical, but what dekko would extract
        # from it has changed, so no amount of file-hash diffing can
        # answer "is this map still correct" — treat it as stale
        # outright, once, until the next `dekko map` re-stamps it.
        # Both signals (and the raw values behind them) are carried on
        # the verdict so a caller can tell the two apart — a
        # long-lived process (``dekko serve``) can have an identical
        # ``tool_version`` string on both sides while still running
        # stale extractor code, which ``version_stale`` alone can't
        # distinguish (round-09 §2.3).
        return Freshness(
            fresh=False,
            reason="version",
            version_stale=version_stale,
            spec_stale=spec_stale,
            built_version=built_version,
            running_version=running_version,
            built_spec_hash=built_spec_hash,
            running_spec_hash=running_spec_hash,
        )

    recorded: dict[str, str] = prov.get("files", {})
    recorded_stat: dict[str, list[int]] = prov.get("stat", {})
    current_paths, _ = walker.discover(
        root,
        subpath=prov.get("subpath"),
        excludes=tuple(prov.get("excludes", [])),
        max_file_size=prov.get("max_file_size", walker.DEFAULT_MAX_FILE_SIZE),
    )
    # Fast path: a file whose (mtime, size) signature is unchanged is
    # assumed unchanged and not re-hashed. Files that are new, lack a
    # recorded signature, or whose stat moved fall back to hashing —
    # the content hash remains the decider for those.
    current: dict[str, str] = {}
    for rel in current_paths:
        sig = recorded_stat.get(rel)
        if sig and sig == _stat_sig(root / rel):
            current[rel] = recorded.get(rel, "")
        else:
            current[rel] = _file_hash(root / rel)

    added = sorted(set(current) - set(recorded))
    removed = sorted(set(recorded) - set(current))
    changed = sorted(
        rel
        for rel in set(recorded) & set(current)
        if recorded[rel] != current[rel]
    )
    is_stale = bool(added or removed or changed)
    return Freshness(
        fresh=not is_stale,
        added=added,
        removed=removed,
        changed=changed,
        reason="content" if is_stale else None,
    )


def load_provenance(root: Path) -> dict | None:
    """Freshness-only load: read the provenance sidecar, not the map.

    ``dekko status`` (and any other caller that only needs to answer
    "is this map still fresh") does not need the parsed symbol/call
    graph ``load_map`` builds — only ``doc["provenance"]``. Reading
    the small ``.dekko/provenance.json`` sidecar (written alongside
    ``map.json`` by ``write_provenance_sidecar``) instead of the full
    map document is the win: ``map.json`` can run into the hundreds of
    MB on a large repo, while the sidecar is a few KB.

    The sidecar records the ``(mtime, size)`` signature of the
    ``map.json`` it was written next to (the same fast-path signature
    ``_freshness_from_provenance`` uses for individual source files).
    It is trusted only when that signature still matches — a
    hand-edited, externally regenerated, or otherwise desynced
    ``map.json`` (two independent files, same risk already called out
    for ``cache.json`` in ``repo_ops._map_run_is_noop``'s docstring) falls
    back to a real parse rather than silently trusting stale data.

    Args:
        root: Repository root.

    Returns:
        The provenance dict, or ``None`` when ``map.json`` itself is
        missing (mirrors ``load_map``'s ``None`` in that case, so
        callers can tell "no map at all" from "map exists but has no
        provenance"). Falls back to parsing ``map.json`` directly —
        still cheaper than ``load_map``, since it skips building the
        symbol/call tables — when the sidecar is missing, stale, or
        unreadable.
    """
    map_path = root / _MAP_DIR / "map.json"
    current_sig = _stat_sig(map_path)
    if not current_sig:
        return None
    sidecar = root / _MAP_DIR / _PROVENANCE_FILE
    try:
        doc = _json_loads(sidecar.read_bytes())
    except (OSError, ValueError):
        doc = None
    if isinstance(doc, dict) and doc.get("map_stat") == current_sig:
        prov = doc.get("provenance")
        if isinstance(prov, dict):
            return prov
    try:
        full_doc = _json_loads(map_path.read_bytes())
    except (OSError, ValueError):
        return None
    prov = full_doc.get("provenance") if isinstance(full_doc, dict) else None
    return prov if isinstance(prov, dict) else None


def write_provenance_sidecar(root: Path, provenance: dict) -> None:
    """Write the small provenance-only sidecar next to ``map.json``.

    Lets ``load_provenance`` skip parsing the full ``map.json``
    document. ``map.json`` keeps its own embedded ``"provenance"`` key
    too — for backward compatibility with anything reading it
    directly, and as ``load_provenance``'s fallback when this sidecar
    is missing or stale. Must be called immediately after ``map.json``
    itself is written, so the recorded ``map_stat`` signature actually
    matches the file on disk.

    Args:
        root: Repository root; the sidecar is written under its
            ``.dekko/`` directory, which the caller is expected to
            have already created (e.g. via ``cache.ensure_dir``).
        provenance: The same provenance dict just embedded in
            ``map.json``.
    """
    map_path = root / _MAP_DIR / "map.json"
    path = root / _MAP_DIR / _PROVENANCE_FILE
    doc = {"provenance": provenance, "map_stat": _stat_sig(map_path)}
    atomic_write_bytes(path, _json_dumps(doc))
