"""Render the extracted symbol/call graph as MAP.md."""

import re
from collections import Counter
from datetime import datetime, timezone

from model import CallGraph, FileMap, Symbol
from resolver import MODULE_CALLER_SUFFIX

_SLUG = re.compile(r"[^a-z0-9]+")


class _Anchors:
    """Stable, unique markdown anchor ids for files and symbols."""

    def __init__(self) -> None:
        self._by_key: dict[str, str] = {}
        self._used: set[str] = set()

    def get(self, key: str) -> str:
        """Return the anchor id for a file path or symbol id."""
        anchor = self._by_key.get(key)
        if anchor is not None:
            return anchor
        base = _SLUG.sub("-", key.lower()).strip("-") or "x"
        anchor = base
        counter = 2
        while anchor in self._used:
            anchor = f"{base}-{counter}"
            counter += 1
        self._used.add(anchor)
        self._by_key[key] = anchor
        return anchor


def signature(sym: Symbol) -> str:
    """Format a symbol as a one-line signature."""
    if sym.kind == "class":
        return f"class {sym.qualname}"
    parts = [f"{p.name}: {p.type}" if p.type else p.name for p in sym.params]
    sig = f"{sym.qualname}({', '.join(parts)})"
    if sym.returns:
        sig += f" -> {sym.returns}"
    return sig


def render_markdown(
    files: list[FileMap], graph: CallGraph, root_label: str
) -> str:
    """Render the full MAP.md document.

    Args:
        files: Per-file extraction results, in output order.
        graph: Resolved call graph.
        root_label: Display name of the mapped root.

    Returns:
        The complete markdown text.
    """
    anchors = _Anchors()
    symbols_by_id = {sym.id: sym for fm in files for sym in fm.symbols}
    ambiguous_by_caller: dict[str, list[tuple[str, int]]] = {}
    for caller, name, cands in graph.ambiguous:
        ambiguous_by_caller.setdefault(caller, []).append((name, len(cands)))

    lines = _header(files, graph, root_label)
    lines += _toc(files, anchors)
    for fm in files:
        lines += _file_section(
            fm, graph, symbols_by_id, ambiguous_by_caller, anchors
        )
    return "\n".join(lines) + "\n"


def _header(
    files: list[FileMap], graph: CallGraph, root_label: str
) -> list[str]:
    """Document title and stats block."""
    by_lang = Counter(fm.language for fm in files)
    funcs = sum(
        1
        for fm in files
        for s in fm.symbols
        if s.kind in ("function", "method")
    )
    classes = sum(1 for fm in files for s in fm.symbols if s.kind == "class")
    when = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    langs = ", ".join(f"{lang} {n}" for lang, n in by_lang.most_common())
    return [
        f"# Code Map — {root_label}",
        "",
        f"Generated by lidar on {when}. Do not edit by hand.",
        "",
        f"**{len(files)}** files ({langs}) · "
        f"**{funcs}** functions/methods · **{classes}** classes · "
        f"**{len(graph.edges)}** call edges "
        f"({len(graph.ambiguous)} ambiguous, "
        f"{len(graph.external)} external — see map.json)",
        "",
    ]


def _toc(files: list[FileMap], anchors: _Anchors) -> list[str]:
    """Table of contents grouped by directory."""
    lines = ["## Contents", ""]
    last_dir = None
    for fm in files:
        directory, _, base = fm.path.rpartition("/")
        directory = directory or "."
        if directory != last_dir:
            lines.append(f"- **{directory}/**")
            last_dir = directory
        anchor = anchors.get(fm.path)
        count = len(fm.symbols)
        suffix = f" ({count} symbols)" if count else ""
        if fm.error:
            suffix = " (parse error)"
        lines.append(f"  - [`{base}`](#{anchor}){suffix}")
    lines.append("")
    return lines


def _file_section(
    fm: FileMap,
    graph: CallGraph,
    symbols_by_id: dict[str, Symbol],
    ambiguous_by_caller: dict[str, list[tuple[str, int]]],
    anchors: _Anchors,
) -> list[str]:
    """One ``##`` section per file with all its symbols."""
    lines = [
        "---",
        "",
        f'## <a id="{anchors.get(fm.path)}"></a> `{fm.path}`',
        "",
    ]
    if fm.error:
        lines += [f"*{fm.language} — parse error: {fm.error}*", ""]
        return lines
    lines += [f"*{fm.language} · {len(fm.symbols)} symbols*", ""]
    for sym in fm.symbols:
        lines += _symbol_block(
            sym, graph, symbols_by_id, ambiguous_by_caller, anchors
        )
    return lines


def _symbol_block(
    sym: Symbol,
    graph: CallGraph,
    symbols_by_id: dict[str, Symbol],
    ambiguous_by_caller: dict[str, list[tuple[str, int]]],
    anchors: _Anchors,
) -> list[str]:
    """Heading + relations for one symbol."""
    anchor = anchors.get(sym.id)
    lines = [
        f'### <a id="{anchor}"></a> `{signature(sym)}`',
        "",
        f"*{sym.kind} · lines {sym.start_line}-{sym.end_line}*",
        "",
    ]
    relations = _relations(
        sym, graph, symbols_by_id, ambiguous_by_caller, anchors
    )
    if relations:
        lines += [*relations, ""]
    return lines


def _relations(
    sym: Symbol,
    graph: CallGraph,
    symbols_by_id: dict[str, Symbol],
    ambiguous_by_caller: dict[str, list[tuple[str, int]]],
    anchors: _Anchors,
) -> list[str]:
    """``calls`` / ``called by`` bullet lines for a symbol."""
    lines = []
    out_links = [
        _link(callee, symbols_by_id, anchors)
        for callee in graph.calls_out.get(sym.id, [])
    ]
    for name, count in ambiguous_by_caller.get(sym.id, []):
        out_links.append(f"`{name}` *(ambiguous: {count} candidates)*")
    if out_links:
        lines.append(f"- **calls:** {', '.join(out_links)}")
    in_links = [
        _link(caller, symbols_by_id, anchors)
        for caller in graph.calls_in.get(sym.id, [])
    ]
    if in_links:
        lines.append(f"- **called by:** {', '.join(in_links)}")
    return lines


def _link(
    sym_id: str, symbols_by_id: dict[str, Symbol], anchors: _Anchors
) -> str:
    """Markdown link to a symbol, or a plain label for top level."""
    if sym_id.endswith(MODULE_CALLER_SUFFIX):
        path = sym_id[: -len(MODULE_CALLER_SUFFIX)]
        return f"top level of [`{path}`](#{anchors.get(path)})"
    sym = symbols_by_id.get(sym_id)
    if sym is None:
        return f"`{sym_id}`"
    return f"[`{sym.qualname}`](#{anchors.get(sym_id)})"
